apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-hackathon-01
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aws-hackathon-01
  template:
    metadata:
      labels:
        app: aws-hackathon-01
    spec:
      containers:
      - name: aws-hackathon-01
        image: soundararajanltim/aws-hackathon-01:v1
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: docker-hub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: NodePort
